In [ ]:
import numpy as np

In [ ]:
a = np.random.normal(10, 5, (2,3))

In [ ]:
a

array([[ 6.42196563, 11.36033705,  7.04063369],
       [14.26513044,  4.78270087, 14.73243277]])

In [ ]:
list1 = [1,2,3,4]
a = np.array(list1)

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.shape

(4,)

In [ ]:
b = np.array([[1,2,3],[4,5,6]])
b.shape

(2, 3)

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.array(range(20)).reshape((4,5)) # reshape 메소드로 행렬의 차원변경 가능

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
np.array(range(8)).reshape((-1,5))

ValueError: ignored

In [ ]:
a = [1,2,3,4,5] # 리스트 indexing

In [ ]:
a[:3]

[1, 2, 3]

In [ ]:
a = np.array([1,2,3])

In [ ]:
a.shape

(3,)

In [ ]:
a[2]

3

In [ ]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)

In [ ]:
b.shape

(2, 3)

In [ ]:
b[0]  # b[:1] 같은 내용

array([1.5, 2. , 3. ])

In [ ]:
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype = float)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [ ]:
c[1,]

array([[3., 2., 1.],
       [4., 5., 6.]])

In [ ]:
a < 2 # [1,2,3]에서 2보다 작은 

array([ True, False, False])

In [ ]:
a[a != 2 ] # 조건식을 True 만족하는 원소만 뽑아보기.

array([1, 3])

In [ ]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [ ]:
b[[1,0,1,0], [0,1,2,0]]

array([4. , 2. , 6. , 1.5])

In [ ]:
b[[1,0,1,0]][:, [0,1,2,0]]

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [ ]:
a + b     # 벡터연산 원소끼리의 연산 가능ㅛ

array([5, 7, 9])

In [ ]:
x = [1,2,3]
y = [4,5,6]

In [ ]:
x + y   # 리스트에서는 원소끼리 연산 불가. + 하면 리스트 연결.

[1, 2, 3, 4, 5, 6]

In [ ]:
a

array([1, 2, 3])

In [ ]:
b

array([4, 5, 6])

In [ ]:
a + b

array([5, 7, 9])

In [ ]:
np.add(a, b)

array([5, 7, 9])

In [ ]:
a + 5

array([1, 2, 3])

In [ ]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
a.sum()

10

In [ ]:
a.min()

1

In [ ]:
a.max()

4

In [ ]:
a.sum()

10

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
np.sum(a, axis=0)

array([4, 6])

In [ ]:
np.mean(a, axis= 1)

array([1.5, 3.5])

In [79]:
a

array([[1, 2],
       [3, 4]])

In [84]:
np.where(a==3)   # 값value로 index번호 찾기

(array([1]), array([0]))

In [87]:
?np.argmin()